# token
@TOKEN = 

### health check
GET http://localhost:3000/health HTTP/1.1

### GET tasks
GET http://localhost:3000/v1/tasks HTTP/1.1
Authorization: Bearer {{TOKEN}}

### POST task
POST http://localhost:3000/v1/tasks HTTP/1.1
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "name": "Implement Strategy Pattern"
}

### PUT task
PUT http://localhost:3000/v1/tasks/cmcxm7ax40001vk82r3h9xpdc HTTP/1.1
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "project_id": "cmcxheczy0000vkkmqrqysta0"
}

### GET task by ID
GET http://localhost:3000/v1/tasks/cmcxhed1a0002vkkmgt9pbfft HTTP/1.1
Authorization: Bearer {{TOKEN}}

### GET projects
GET http://localhost:3000/v1/projects HTTP/1.1
Authorization: Bearer {{TOKEN}}

### POST project
POST http://localhost:3000/v1/projects HTTP/1.1
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "name": "Project 2",
  "description": "This is a test project"
}

### GET project by ID
GET http://localhost:3000/v1/projects/cmcxheczy0000vkkmqrqysta0 HTTP/1.1
Authorization: Bearer {{TOKEN}}

### GET project's tasks
GET http://localhost:3000/v1/projects/cmcxheczy0000vkkmqrqysta0/tasks HTTP/1.1
Authorization: Bearer {{TOKEN}}