services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: mysql://root:secret@db:3306/task_manager
      NODE_ENV: production

      APP_SECRET: your_app_secret
      ISSUER_BASE_URL: your_issuer_base_url
      AUDIENCE: your_audience

      MAIL_MAILER: smtp
      MAIL_HOST: your_mail_host
      MAIL_PORT: your_mail_port
      MAIL_USERNAME: your_mail_username
      MAIL_PASSWORD: your_mail_password
      ADMIN_EMAIL: your_admin_email
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: task_manager
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 2s
      timeout: 20s
      retries: 10

volumes:
  db-data:
